from typing import AsyncGenerator
from google import genai

from app.core.config import settings
from app.services.core.base_text import BaseTextProvider

class GoogleTextProvider:
    """
    Implementation of the BaseTextProvider for Google GenAI.
    Handles text generation using models like Gemini 2.5 Flash/Pro.
    """

    def __init__(self, model_name: str = "gemini-2.5-flash"):
        """
        Initializes the Google client.
        
        Args:
            model_name (str): The specific Gemini model to use.
        """
        ## Create the google genai client
        self.client = genai.Client(api_key=settings.google_api_key)
        self.model_name = model_name

    async def generate_text(self, prompt: str) -> str:
        """
        Generates a complete text response.
        
        Args:
            prompt (str): The user's prompt.
            
        Returns:
            str: The full generated text from Gemini.
        """
        ## use asynchronous aio
        response = await self.client.aio.models.generate_content(
            model=self.model_name,
            contents=prompt
        )
        return response.text

    async def generate_stream(self, prompt: str) -> AsyncGenerator[str, None]:
        """
        Generates text as a stream of chunks.
        
        Args:
            prompt (str): The user's prompt.
            
        Yields:
            str: Chunks of text as they are generated by Gemini.
        """
        response_stream = await self.client.aio.models.generate_content_stream(
            model=self.model_name,
            contents=prompt
        )
        
        async for chunk in response_stream:
            if chunk.text:
                yield chunk.text

_provider_check: BaseTextProvider = GoogleTextProvider()