from platformdirs import site_config_dir
import os
from enum import Enum
from pydantic_settings import (
    BaseSettings, 
    SettingsConfigDict, 
    PydanticBaseSettingsSource, 
    TomlConfigSettingsSource
)

app_name = "Ratatoskr"
app_author = "Phantom"
global_dir = site_config_dir(appname=app_name, appauthor=app_author)
settings_path = os.path.join(global_dir, "settings.toml")

class DbAccessMethod(Enum):
    LOCAL = "local"
    # DRIVE = "drive"
    # SERVER = "server"

class Settings(BaseSettings):
    app_name: str = "Ratatoskr"
    service_name: str = "Ratatoskr Daemon"
    
    ## Point to the directory, not the file
    settings_folder: str = global_dir 

    ## Always provide a default empty value to prevent crashes on first startup
    google_api_key: str = ""

    db_access_method: DbAccessMethod = DbAccessMethod.LOCAL
    database_name: str = "ratatoskr"

    ## Instruct Pydantic to read the actual file generated by platformdirs
    model_config = SettingsConfigDict(
        toml_file=settings_path, 
        env_file=".env", 
        env_file_encoding="utf-8"
    )
    
    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource,
    ) -> tuple[PydanticBaseSettingsSource, ...]:
        ## TOML is placed before ENV to make it the primary source of truth
        return (
            init_settings,
            TomlConfigSettingsSource(settings_cls),
            env_settings,
            dotenv_settings,
        )

settings = Settings()